######################################################################
# Automatically generated by qmake (1.07a) Sun Jan 2 22:39:24 2005
######################################################################
QT += svg xml
TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += testqt.cpp


